name: deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      - name: Create example frontend .env.production
        run: echo ${{ secrets.EXAMPLE_FRONTEND_PRODUCTION_ENV }} | base64 -d > ./examples/frontend/.env.production
      - name: Install Dependencies
        run: yarn
      - name: Prepare release
        run: yarn prerelease
      - name: Deploy
        run: yarn deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
