name: deploy

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Create example frontend .env.production
        run: echo ${{ secrets.EXAMPLE_FRONTEND_PRODUCTION_ENV }} | base64 -d > ./examples/frontend/.env.production

      - name: Install Dependencies
        run: yarn --immutable

      - name: Prepare release
        run: yarn prerelease

      - name: Deploy
        run: yarn deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bitphinix/slate-yjs-example-backend
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./examples/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
